### PR TITLE
Capability addition to run using a debug build of UFSWM

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## PR Checklist
- [X] This PR has been tested on an RDHPCS machine and/or WCOSS2. Please select below:
  - [X] RDHPCS.
  - [ ] WCOSS2. (Waiting on Dogwood/Cactus to come back)

- [X] This PR has been tested with the ufs-srweather-app workflow online-cmaq branch. (Confirmed through discussions with @JianpingHuang-NOAA )

- [ ] New or updated input data is required by this PR. 

- [X] Baselines are expected to change.

## Description

This PR removes a locally edited version of aero_depv.F in favor of the CMAQ version.
Also to be noted is that using init_concentrations = true in aqm.rc will cause debug build to fail at runtime. I have conversed with @JianpingHuang-NOAA who stated that init_concentrations is set to false in the operational setting.

## Issue(s) addressed

- Linked with #44 (does not close, until in develop branch) 

## Dependencies

No Dependencies.

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
[RegressionTests_wcoss2.intel.log](https://github.com/NOAA-EMC/AQM/files/10875012/RegressionTests_wcoss2.intel.log)
[RegressionTests_wcoss2.intel.proof.log](https://github.com/NOAA-EMC/AQM/files/10875022/RegressionTests_wcoss2.intel.proof.log)

Proof log shows no debug baseline and fails regional_atmaq
log shows reproduces with new baselines.

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA Please review.

**Review by JianpingHuang-NOAA — COMMENTED** [review]
One more comment but not directly related to this change.  Is "-D32BIT=ON" included in the  CMAKE_FLAGS for the UFSWM compilation for AQM app.?

**Comment by BrianCurtis-NOAA** [comment]
> One more comment but not directly related to this change. Is "-D32BIT=ON" included in the CMAKE_FLAGS for the UFSWM compilation for AQM app.?

No, we do not use -D32BIT=ON, should we?

**Comment by JianpingHuang-NOAA** [comment]
I have included "use -D32BIT=ON" when I compiled the ufswm code. It does not affect the results but may save about 5% fcst model running time.  Please include it for aqm application.

**Comment by JianpingHuang-NOAA** [comment]
Do we need another PR on the change of -D32BIT=ON?

**Comment by BrianCurtis-NOAA** [comment]
> Do we need another PR on the change of -D32BIT=ON?

I've already added it to this PR in UFSWM. I'm running RT's now.

I want to confirm, you ran the Science tests for this PR with -D32BIT=ON, correct?

**Comment by JianpingHuang-NOAA** [comment]
I thinks so. It is originally suggested by Barry.  Actually I have included it into all of my retro and NRT runs.

**Review by JianpingHuang-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
UFSWM RT's were reproducible. Merging this in.

**Pull request merged**
