### PR TITLE
Revert fixes to get debug mode working with UFSWM debug run

### LINKED ISSUE #56: The latest workflow got strange O3 and PM2.5 predictions
I tested the latest workflow and noticed that the UFS-AQM got very strange behavior for both O3 nd PM2.5 predictions.  It seems that the model is not able to read emissions  correctly ?

plot_grp1 timeseries OZONE 2022-07-01_12 2022-07-18_12 all CONUS
plot_grp1 timeseries PM2 5 2022-07-01_12 2022-07-18_12 all CONUS

@chan-hoo @BrianCurtis-NOAA @bbakernoaa

### LINKED ISSUE #58: PM2.5 underprediction by the latest online-cmaq SRW workflow
I completed a 22-day test run (July 4-25, 2022) by using the SRW workflow with a hash number of 5fdee93 (https://github.com/ufs-community/ufs-srweather-app/tree/online-cmaq) and noticed that PM2.5 was under-predicted especially in EPA-defined Regions , R6 and R4 while O3 predictions are fine. 

plot_grp1 timeseries PM2 5 2022-07-01_12 2022-07-26_12 epa_region R6

This issue was observed by Kai recent run last week on Cactus.

After I turned on printing out ESMF log file, and also noticed the fire PM2.5 composition emissions are not read in correctly as illustrated by the following line example 

================================
20230126 231211.602 INFO             PET0000       AQM: emissions: fire: read: PNCOM           : min/max =        0.0000000           0.0000000

More details can be found from personal workflow and run dir on Dogwood

1) My workflow/ush: /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.53  (Dogwood)

2) An example case run for 20220717:  /lfs/h2/emc/aqmtemp/para/tmp/run_fcst.id_1674697912_2022071712

@chan-hoo @bbakernoaa @KaiWang-NOAA

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
## PR Checklist
- [X] This PR has been tested on an RDHPCS machine and/or WCOSS2. Please select below:
  - [X] RDHPCS (Brian, UFSWM ATMAQ RT).
  - [X] WCOSS2 (Jianping, 30hr w/workflow).

- [X] This PR has been tested with the ufs-srweather-app workflow online-cmaq branch.

- [ ] New or updated input data is required by this PR. 

- [X] Baselines are expected to change.

## Description

This PR reverts an update made to get the model to run with the UFSWM in Debug mode. Those changes were causing an odd behavior with retro runs.

## Issue(s) addressed

 - Closes #56 
 - Closes #58 

## Dependencies

No Dependencies

### CODE REVIEW

**Comment by JianpingHuang-NOAA** [comment]
@BrianCurtis-NOAA   Do  I need to redo a test?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA Do I need to redo a test?

You tested this branch. Should not need to do another test.

**Review by bbakernoaa — APPROVED** [review]

**Review by JianpingHuang-NOAA — COMMENTED** [review]
I saw that both following sections were taken out to address division by zero issue now

IF (CONC( NO2_MAP,1 ) .NE. 0) THEN
                      DEPV_HNO3 = DEPVCR( V ) + PLDV_HONO / CONC( NO2_MAP,1 )
                  ELSE
                      DEPV_HNO3 = DEPVCR( V )
                  END IF
IF (CONC( NO2_MAP,1 ) .NE. 0) THEN
                      DEPV_HNO3 = DEPVCR( V ) + PLDV_HONO / CONC( NO2_MAP,1 )
                  ELSE
                      DEPV_HNO3 = DEPVCR( V )
                  END IF

**Comment by BrianCurtis-NOAA** [comment]
> I saw that both following sections were taken out to address division by zero issue now

Yes, I will be addressing this in another PR.

**Review by JianpingHuang-NOAA — APPROVED** [review]
Thanks !

**Pull request merged**
