### PR TITLE
Feature/pt source

### PR DESCRIPTION
**Pull request by ytangnoaa**
This is the AQM code change part of point-source emissions

For detail, please see

https://github.com/NOAA-EMC/AQM/issues/13

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@ytangnoaa Could you please bring this up-to-date with NOAA-EMC/develop branch?

**Comment by ytangnoaa** [comment]
Brian
It was updated. See https://github.com/noaa-oar-arl/AQM/pull/10

Thanks

Youhua

**Comment by JianpingHuang-NOAA** [comment]
Hi Brain and Chan-Hoo,

Is this PR ready to test?

**Comment by JianpingHuang-NOAA** [comment]
Hi Youhua,

It failed with following error message when I tested point-source code.

20221030 153123.833 ERROR            PET0000 aqmio.F90:1238        - Field CO not defined in NetCDF data set (strerr=NetCDF: Variable not found, ncerrToCheck=-49)

Please see PET0000.ESMF_LogFile at

 /lfs/h2/emc/ptmp/jianping.huang/emc.para/tmp/run_fcst.17178779.cbqs01 

Jianping

**Comment by BrianCurtis-NOAA** [comment]
@ytangnoaa @bbakernoaa @JianpingHuang-NOAA How is the progress for this? Are the issues with this codebase going to be fixed and available for a PR by the end of next week 11/19? Or should this be skipped for operational implementation?

**Comment by ytangnoaa** [comment]
> @ytangnoaa @bbakernoaa @JianpingHuang-NOAA How is the progress for this? Are the issues with this codebase going to be fixed and available for a PR by the end of next week 11/19? Or should this be skipped for operational implementation?

Brian, Jianping tested this PR, and it worked as expected. However, it yielded higher surface PM2.5, and we might need longer time evaluation.

**Comment by BrianCurtis-NOAA** [comment]
@bbakernoaa @ytangnoaa is this ready for merge and testing with UFSWM ? Deadline is Wed.

**Comment by ytangnoaa** [comment]
> @bbakernoaa @ytangnoaa is this ready for merge and testing with UFSWM ? Deadline is Wed.

Brian, thank you for asking. After the bug fixing, the PM2.5 overprediction issue should be resolved. This C18 testing run included this PR. If there is no further comment, you may go ahead to merge it.

**Comment by HaixiaLiu-NOAA** [comment]
@BrianCurtis-NOAA @ytangnoaa Could you please add reviewers for this PR? Does this PR require reviewers' approval before merging?

**Comment by ytangnoaa** [comment]
> @BrianCurtis-NOAA @ytangnoaa Could you please add reviewers for this PR? Does this PR require reviewers' approval before merging?

I can not add reviewers to this PR. Could Brian help it? Thanks

**Comment by BrianCurtis-NOAA** [comment]
I've added reviewers. I'd prefer at least 2 reviews before we go to UFSWM with a PR.

**Comment by JianpingHuang-NOAA** [comment]
@bbakernoaa  Hi Barry, can you help us to check whether the point-source emissions have been removed from the NEXUS calculation since I can not find them in my C15 and C19 NRT runs?

Please check the NEXUS config file at /lfs/h2/emc/physics/noscrub/jianping.huang/nwdev/packages/aqm.v7.0.15/sorc/arl_nexus/config/cmaq

**Comment by bbakernoaa** [comment]
@JianpingHuang-NOAA Is C15 and C19 without point sources in plume rise? I can't keep track of these

**Comment by JianpingHuang-NOAA** [comment]
@bbakernoaa  I thought C15 and C19 put all the point-source emissions at Level 1. However, I did not see the PT emissions in the NEUS config file. I want to know whether the point source emissions have been removed from the NEXUS  calculation by default settings.

**Comment by bbakernoaa** [comment]
To answer that question yes the point sources were removed from the nexus_config file to support the other point source method and to ensure not double counting

**Comment by JianpingHuang-NOAA** [comment]
Ok, thanks for the confirmation. This means that point-source emissions
were not included in our simulations for C15 and C19. This helps us better
understand the difference of predicted O3 and PM2.5 among C15, C18, and C19
that I presented on 11/29/2022 (here
<https://docs.google.com/presentation/d/1E4o2wKgc2MY6I5TPWKQghU0oVBR2904o/edit#slide=id.g19cf18cd5b5_0_33>
)

**Comment by BrianCurtis-NOAA** [comment]
With Raffaele's point source code in the repo, I will close this PR. Please let me know if this is in error.

**Pull request closed without merging**
