### PR TITLE
Update CMake build system

### PR DESCRIPTION
**Pull request by rmontuoro**
This PR includes changes to address the following issues:

- #10 
- #14 

A [UFS weather model branch](https://github.com/rmontuoro/ufs-weather-model/tree/bugfix/aqm-build-system) is also available to test these changes:
```
git clone -b bugfix/aqm-build-system --recursive https://github.com/rmontuoro/ufs-weather-model
```

### CODE REVIEW

**Comment by BrianCurtis-NOAA** [comment]
@rmontuoro Where did you find the debug flags? I've searched for a bit in documentation and through the code repo and haven't found anything yet. The documentation is large, so I suspect I just haven't found it yet.

**Comment by rmontuoro** [comment]
@BrianCurtis-NOAA - They are in the configuration script for CMAQ included in the EPA repository:
https://github.com/USEPA/CMAQ/blob/be5d28fd1b60522e6fc98aefeead20e6aac3530b/config_cmaq.csh#L90-L103

**Comment by BrianCurtis-NOAA** [comment]
> They are in the configuration script for CMAQ included in the EPA repository: https://github.com/USEPA/CMAQ/blob/be5d28fd1b60522e6fc98aefeead20e6aac3530b/config_cmaq.csh#L90-L103

Thank you! I cast a wide net for "Debug, debug, DEBUG". I did not think of DBG.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Review by JianpingHuang-NOAA — COMMENTED** [review]
It reads good to me

**Pull request merged**
