### PR TITLE
Remove compiler warnings and remarks for AQMv7 implementation

### PR DESCRIPTION
**Pull request by rmontuoro**
## PR Checklist
- [x] This PR has been tested on an RDHPCS machine and/or WCOSS2. Please select below:
  - [ ] RDHPCS.
  - [X] WCOSS2.

- [x] This PR has been tested with the ufs-srweather-app workflow online-cmaq branch.

- [ ] New or updated input data is required by this PR. 

- [ ] Baselines are expected to change.

## Issue(s) addressed

This PR removes the compiler warnings referenced in Issue #93 and fixes edit descriptors in the original CMAQ source code leading to compiler remarks.

The changes included in this PR passed regression testing on Cactus.

## Dependencies

None

### CODE REVIEW

**Comment by JianpingHuang-NOAA** [comment]
@rmontuoro  Have you done any test on this PR?

**Review by JianpingHuang-NOAA — APPROVED** [review]

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA can you please run AQM with these changes (if you haven't yet) to make sure the results are not changing. I don't expect them to. As soon as you confirm we can merge this.

**Review by BrianCurtis-NOAA — APPROVED** [review]

**Comment by JianpingHuang-NOAA** [comment]
@BrianCurtis-NOAA  I have done the test. Everything is good.  Do we need to open a PR to merge the changes to the ufs-weather-model?

**Comment by BrianCurtis-NOAA** [comment]
> @BrianCurtis-NOAA I have done the test. Everything is good. Do we need to open a PR to merge the changes to the ufs-weather-model?

We can bring these changes into the weather model later. I'll merge this in now.

**Pull request merged**
