### PR TITLE
Calculate PM2.5 from AQM and save it as a 3D tracer in UFSWM

### LINKED ISSUE #21: Missing operational products
Air quality operational products, such as hourly max and average surface concentrations of ozone and PM2.5, need to be output by the model.

### PR DESCRIPTION
**Pull request by BrianCurtis-NOAA**
This PR brings in Raffaele's code to implement production outputs for PM2.5 as well as adjustments to that code that add PM2.5 as a 3D tracer for the UFSWM.

The addition of this code will allow for a PM2.5 Avg/Min/Max calculation for production outputs.

- fixes #21

### CODE REVIEW

**Comment by yangfanglin** [comment]
Is the PM2.5 product for users a 2D field ?    Is it possible to avoid using a 3D array ?

**Comment by BrianCurtis-NOAA** [comment]
> Is the PM2.5 product for users a 2D field ? Is it possible to avoid using a 3D array ?

Here: https://github.com/NOAA-EMC/AQM/blob/02b2bb3f64c73d60b78b82d00198df98e24d53f9/src/drv/cmaq_mod.F90#L792 you can define the number of layers as the input, so you can make it a 2D array with nlays_in=1 or 3D with a number > 1. Will this suffice?

**Comment by BrianCurtis-NOAA** [comment]
@JianpingHuang-NOAA @rmontuoro We are ready for merge into UFSWM, will one of you please review the code changes.

**Comment by JianpingHuang-NOAA** [comment]
The code was tested with 48-hr simulations for the large domain successfully. I did not see an impact on the forecast model runtime. It will be helpful if a flag is added in the aqm.rc file that allows us to have an option to write out product files.

**Review by rmontuoro — APPROVED** [review]

**Review by JianpingHuang-NOAA — APPROVED** [review]

**Pull request merged**
